### ISSUE TITLE
2B Preamble, give the name of the expected function

### ISSUE THREAD

**Issue by sfgeekgit** [Russ741/karpathy-nn-z2h#7] opened 2023-10-14 00:37 UTC
2B Preamble, doesn't explicitly say what to name the function load_words
This is pretty trivial, as you can see the name of the function called in the test

**Comment by Russ741** [comment] 2023-11-07 22:11
I will fix this as part of #5 - I want all of the function signatures to be visible.

**Comment by Russ741** [comment] 2023-11-07 22:11
Duplicate of #5

**Closed by Russ741** 2023-11-07 22:11 UTC
